"""
QSS Generator - Qt Style Sheet Generator
QSSの自動生成と管理
"""

from dataclasses import dataclass
from typing import Dict, List, Optional
from pathlib import Path


@dataclass
class ColorScheme:
    """カラースキーム"""
    name: str
    primary: str
    secondary: str
    background: str
    surface: str
    text: str
    text_secondary: str
    accent: str
    error: str
    warning: str
    success: str


@dataclass
class ThemeConfig:
    """テーマ設定"""
    name: str
    colors: ColorScheme
    font_family: str = "Segoe UI"
    font_size_base: int = 10
    border_radius: int = 4
    spacing: int = 8


class QSSGenerator:
    """
    QSS Generator

    Features:
    - テーマベースのQSS生成
    - ダークモード/ライトモード
    - コンポーネント別スタイル
    - カスタムカラースキーム
    """

    # デフォルトダークテーマ
    DARK_THEME = ThemeConfig(
        name="Dark",
        colors=ColorScheme(
            name="Dark",
            primary="#2196F3",
            secondary="#64B5F6",
            background="#1e1e1e",
            surface="#2d2d2d",
            text="#ffffff",
            text_secondary="#b0b0b0",
            accent="#4CAF50",
            error="#f44336",
            warning="#ff9800",
            success="#4CAF50"
        )
    )

    # デフォルトライトテーマ
    LIGHT_THEME = ThemeConfig(
        name="Light",
        colors=ColorScheme(
            name="Light",
            primary="#1976D2",
            secondary="#42A5F5",
            background="#ffffff",
            surface="#f5f5f5",
            text="#212121",
            text_secondary="#757575",
            accent="#388E3C",
            error="#D32F2F",
            warning="#F57C00",
            success="#388E3C"
        )
    )

    def __init__(self):
        self.current_theme = self.DARK_THEME

    def set_theme(self, theme: ThemeConfig) -> None:
        """
        テーマを設定

        Args:
            theme: テーマ設定
        """
        self.current_theme = theme

    def generate_base_styles(self) -> str:
        """
        基本スタイルを生成

        Returns:
            QSS文字列
        """
        t = self.current_theme
        c = t.colors

        return f"""
/* Base Styles - {t.name} Theme */
/* Generated by Helix AI Studio QSS Generator */

* {{
    font-family: "{t.font_family}";
    font-size: {t.font_size_base}pt;
}}

QMainWindow {{
    background-color: {c.background};
}}

QWidget {{
    background-color: {c.background};
    color: {c.text};
}}

/* Tab Widget */
QTabWidget::pane {{
    border: 1px solid {c.surface};
    background-color: {c.background};
}}

QTabBar::tab {{
    background-color: {c.surface};
    color: {c.text_secondary};
    padding: {t.spacing}px {t.spacing * 2}px;
    border-top-left-radius: {t.border_radius}px;
    border-top-right-radius: {t.border_radius}px;
}}

QTabBar::tab:selected {{
    background-color: {c.primary};
    color: {c.text};
}}

QTabBar::tab:hover:!selected {{
    background-color: {c.secondary};
}}
"""

    def generate_button_styles(self) -> str:
        """
        ボタンスタイルを生成

        Returns:
            QSS文字列
        """
        t = self.current_theme
        c = t.colors

        return f"""
/* Button Styles */
QPushButton {{
    background-color: {c.primary};
    color: {c.text};
    border: none;
    padding: {t.spacing}px {t.spacing * 2}px;
    border-radius: {t.border_radius}px;
    min-width: 80px;
}}

QPushButton:hover {{
    background-color: {c.secondary};
}}

QPushButton:pressed {{
    background-color: {c.primary};
}}

QPushButton:disabled {{
    background-color: {c.surface};
    color: {c.text_secondary};
}}

/* Success Button */
QPushButton[class="success"] {{
    background-color: {c.success};
}}

/* Warning Button */
QPushButton[class="warning"] {{
    background-color: {c.warning};
}}

/* Error/Danger Button */
QPushButton[class="danger"] {{
    background-color: {c.error};
}}
"""

    def generate_input_styles(self) -> str:
        """
        入力フィールドスタイルを生成

        Returns:
            QSS文字列
        """
        t = self.current_theme
        c = t.colors

        return f"""
/* Input Styles */
QLineEdit, QTextEdit, QPlainTextEdit {{
    background-color: {c.surface};
    color: {c.text};
    border: 1px solid {c.surface};
    border-radius: {t.border_radius}px;
    padding: {t.spacing}px;
}}

QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
    border-color: {c.primary};
}}

QComboBox {{
    background-color: {c.surface};
    color: {c.text};
    border: 1px solid {c.surface};
    border-radius: {t.border_radius}px;
    padding: {t.spacing}px;
    min-width: 100px;
}}

QComboBox::drop-down {{
    border: none;
    width: 20px;
}}

QComboBox QAbstractItemView {{
    background-color: {c.surface};
    color: {c.text};
    selection-background-color: {c.primary};
}}
"""

    def generate_list_styles(self) -> str:
        """
        リストスタイルを生成

        Returns:
            QSS文字列
        """
        t = self.current_theme
        c = t.colors

        return f"""
/* List Styles */
QListWidget, QTreeWidget, QTableWidget {{
    background-color: {c.surface};
    color: {c.text};
    border: 1px solid {c.surface};
    border-radius: {t.border_radius}px;
}}

QListWidget::item, QTreeWidget::item {{
    padding: {t.spacing}px;
}}

QListWidget::item:selected, QTreeWidget::item:selected {{
    background-color: {c.primary};
}}

QListWidget::item:hover, QTreeWidget::item:hover {{
    background-color: {c.secondary};
}}

/* Scrollbar */
QScrollBar:vertical {{
    background-color: {c.background};
    width: 12px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background-color: {c.surface};
    border-radius: 6px;
    min-height: 20px;
}}

QScrollBar::handle:vertical:hover {{
    background-color: {c.text_secondary};
}}
"""

    def generate_full_stylesheet(self) -> str:
        """
        完全なスタイルシートを生成

        Returns:
            完全なQSS文字列
        """
        parts = [
            self.generate_base_styles(),
            self.generate_button_styles(),
            self.generate_input_styles(),
            self.generate_list_styles()
        ]
        return "\n".join(parts)

    def save_stylesheet(self, output_path: str) -> bool:
        """
        スタイルシートをファイルに保存

        Args:
            output_path: 出力先パス

        Returns:
            成功かどうか
        """
        try:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(self.generate_full_stylesheet())
            return True
        except Exception as e:
            print(f"Error saving stylesheet: {e}")
            return False

    def create_custom_theme(
        self,
        name: str,
        primary_color: str,
        is_dark: bool = True
    ) -> ThemeConfig:
        """
        カスタムテーマを作成

        Args:
            name: テーマ名
            primary_color: プライマリカラー
            is_dark: ダークテーマかどうか

        Returns:
            テーマ設定
        """
        base = self.DARK_THEME if is_dark else self.LIGHT_THEME
        colors = ColorScheme(
            name=name,
            primary=primary_color,
            secondary=base.colors.secondary,
            background=base.colors.background,
            surface=base.colors.surface,
            text=base.colors.text,
            text_secondary=base.colors.text_secondary,
            accent=primary_color,
            error=base.colors.error,
            warning=base.colors.warning,
            success=base.colors.success
        )
        return ThemeConfig(name=name, colors=colors)
